title: <p align="center"> Goutam Debnath </p>
logo: /Assets/Images/photo_2024-02-04_18-48-41.jpg
description:  <p align="center">AI Engineer | Data Analyst<br>
  <a href="/Assets/PDFs/Resume 4(1).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/goutam-debnath-379597199/">LinkedIn</a> |
  <a href="https://github.com/Debnath-Goutam">GitHub</a></br>

  <br>Currently enhancing my AI/ML expertise at IIIT Bangalore and working at TCS. Passionate about Non-Invasive BCI, Spatial Computation, and gaming. My GitHub reflects my journey in AI/ML. Let's connect to discuss the future of technology! 😊</br></p>
  

show_downloads: false
theme: jekyll-theme-minimal
